import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import controller.DatabaseProcess;
import obj.*;
import javax.swing.*;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NextBook.java
 *
 * Created on Sep 28, 2011, 8:17:03 PM
 */
/**
 *
 * @author jih748
 */
public class NextBook extends javax.swing.JFrame {
    /** Creates new form NextBook */
    public NextBook() {
        initComponents();
        this.setBounds(500, 300, 660, 540);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NextBook");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18));
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 200, 90, 30);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18));
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 240, 110, 23);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(250, 280, 90, 29);

        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 280, 110, 29);

        jTextField1.setText("");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(260, 200, 190, 28);

        jPasswordField1.setText("");
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(260, 240, 190, 28);

        message = new JLabel();
        message.setFont(new java.awt.Font("Verdana", 0, 18));
        message.setForeground(new java.awt.Color(204, 255, 255));
        message.setBounds(200, 350, 300, 28);
        message.setVisible(true);
        getContentPane().add(message);

        jLabel1.setIcon(new javax.swing.ImageIcon("src/assets/login_pic.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 660, 540);

        jButton1.addKeyListener(new KeyListener() {
            @Override
            public void keyPressed(KeyEvent arg0) {}
            @Override
            public void keyReleased(KeyEvent arg0) {
                if (arg0.getKeyCode() == KeyEvent.VK_ENTER) {
                    jButton1ActionPerformed(null);
                }
            }
            @Override
            public void keyTyped(KeyEvent e) {}
        });
        jButton2.addKeyListener(new KeyListener() {
            @Override
            public void keyPressed(KeyEvent arg0) {}
            @Override
            public void keyReleased(KeyEvent arg0) {
                if (arg0.getKeyCode() == KeyEvent.VK_ENTER) {
                    jButton1ActionPerformed(null);
                }
            }
            @Override
            public void keyTyped(KeyEvent e) {}
        });
        jTextField1.addKeyListener(new KeyListener() {
            @Override
            public void keyPressed(KeyEvent arg0) {}
            @Override
            public void keyReleased(KeyEvent arg0) {
                if (arg0.getKeyCode() == KeyEvent.VK_ENTER) {
                    jButton1ActionPerformed(null);
                }
            }
            @Override
            public void keyTyped(KeyEvent e) {}
        });
        jPasswordField1.addKeyListener(new KeyListener() {
            @Override
            public void keyPressed(KeyEvent arg0) {}
            @Override
            public void keyReleased(KeyEvent arg0) {
                if (arg0.getKeyCode() == KeyEvent.VK_ENTER) {
                    jButton1ActionPerformed(null);
                }
            }
            @Override
            public void keyTyped(KeyEvent e) {}
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            DatabaseProcess db = DatabaseProcess.getInstance();
            String username = jTextField1.getText();
            String password = jPasswordField1.getText();
            if(db.checkLogin(username, password)) {
                //System.out.println("Success!");
                new Controller(new User(username,password)).setVisible(true);
                this.setVisible(false);
            } else {
                message.setText("Invalid user credentials");
            }
        } catch (Exception e) {
            message.setText("Something failed logging in");
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        int result;
        try {
            DatabaseProcess db = DatabaseProcess.getInstance();
            String username = jTextField1.getText();
            String password = jPasswordField1.getText();
            User newUser = new User(username,password);
            result = db.createUser(newUser);
            if(result == -1) {
                message.setText("Username taken");
            } else if (result == -2) {
                message.setText("Cannot enter blank values");
            } else {
                message.setText("Success!");
            }
        } catch (Exception e) {
            message.setText("Something failed registering");
            return;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NextBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NextBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NextBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NextBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NextBook().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
